- hosts: all
  tasks:
        - name: Recreate the app1 container  
          docker_container:
                name: app1
                image: neerajsinghnegi/foodvybe:app2
                recreate: yes
                state: present
                ports:
                  - "8080:3000"